package com.xg.rules;

import com.xg.drools.Account;
import com.xg.util.OutPutDisplay;


dialect  "mvel"
// list any import classes here.


//declare any global variabies here.
global OutPutDisplay showResult;



rule "lession1"  //unique rule name.
  when
    Account(  )
  then
    System.out.println("The account is exits");
//    使用定义的全局变量
    showResult.showText("The account is exits");
end

rule "lession2"
  when

  then

end