package com.xg.rules.lesson2;

import com.xg.drools.Account;
import com.xg.util.OutPutDisplay;
import com.xg.drools.CashFlow;
import com.xg.drools.AccountingPeriod;
import java.util.Date;

dialect  "mvel"
// list any import classes here.

//declare any global variabies here.
global OutPutDisplay showResult;

declare Person
  age: int
  name: String
  bir: Date
end


rule "first"  //unique rule name.
  when
    $cash : CashFlow( $mvDate: date, type == CashFlow.CREDIT);
  then
    showResult.showText($mvDate.toString() + "test CashFlow -------");
end

rule "second"
  when
    $cash : CashFlow(type == CashFlow.CREDIT);
    $acc : Account( );
  then
    $acc.setBalance($cash.getAmount()+$acc.getBalance());
    showResult.showText("the account balance = " + $acc.getBalance());
end

rule "three"
  when

  then
    Person person = new Person();
end
