package com.xg.rules;

import com.xg.drools.Account;
import com.xg.util.OutPutDisplay;
import com.xg.drools.CashFlow;
import com.xg.drools.AccountingPeriod;

dialect  "mvel"
// list any import classes here.


//declare any global variabies here.
global OutPutDisplay showResult;



rule "first rule revisited again"  //unique rule name.
  when
    Account(  )
  then
//    使用定义的全局变量
    showResult.showText("The account is exits");
end
