package com.xg.rules.lesson2;

import com.xg.drools.Account;
import com.xg.util.OutPutDisplay;
import com.xg.drools.CashFlow;
import com.xg.drools.AccountingPeriod;

dialect  "mvel"
// list any import classes here.

//declare any global variabies here.
global OutPutDisplay showResult;

rule "first"  //unique rule name.
  when
    $cash : CashFlow( $mvDate: date, type == CashFlow.CREDIT);
  then
    showResult.showText($mvDate.toString() + "test CashFlow -------");
end
